import phone from './phone';
import sms from './sms';
import setPassword from './setPassword';
import _tradePwdCheck from './tradePwdCheck';
import password from './password';
import setTradePwd from './setTradePwd';
import tradePwd from './tradePwd';
import _tradeAuth from './tradeAuth';
import _login from './login';
import _modifyPwd from './modifyPwd';
import oldNewPwd from './oldNewPwd';
import newTradePwd from './newTradePwd';
import _modifyTradePwd from './modifyTradePwd';
import _passwordCheck from './passwordCheck';
export { phone, sms, setPassword, _login, password, _tradePwdCheck, setTradePwd, _tradeAuth, tradePwd, _modifyPwd, oldNewPwd, newTradePwd, _modifyTradePwd, _passwordCheck };
